### PR TITLE
Add support to save acre radios

### PR DESCRIPTION
**Pull request by Drofseh**
- add a function to filter acre radios
- add check to see if either ACRE or TFAR are loaded before running their respective functions

### CODE REVIEW

**Comment by Drofseh** [comment]
the `isClass` checks for ACRE and TFAR should probably be done earlier and set as a global variable that can be referenced later.

I'm not sure where the best place for that would be.

**Comment by Drofseh** [comment]
I also don't see where radios in a player inventory are being filtered.
I don't know how TFAR handles things, but if ACRE has duplicate radio IDs it gets unhappy.

**Comment by McDiod** [comment]
> the isClass checks for ACRE and TFAR should probably be done earlier and set as a global variable

I agree.

> I also don't see where radios in a player inventory are being filtered.

Looks like it doesn't actually. Has to be added. Good find.

I will merge this into a separate branch so I can add those two things. I assume you have tested the ACRE portion of this functionality? We don't use it so I wouldn't know what to look for.

**Comment by Drofseh** [comment]
> where radios in a player inventory are being filtered.

I've taken care of this for ACRE radios and added an empty code block where a TFAR specific function can be called

> I will merge this into a separate branch so I can add those two things. I assume you have tested the ACRE portion of this functionality? We don't use it so I wouldn't know what to look for.

Sounds good to me, I tested all the ACRE stuff and it works as expected

**Pull request merged**
